reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create, :show]

  root to: 'subs#index'
end

reddit_clone/app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  belongs_to :author, primary_key: :id, foreign_key: :author_id, class_name: :User

  has_many :post_subs, dependent: :destroy, inverse_of: :post
  has_many :subs, through: :post_subs
  has_many :comments

  def comments_by_parent_id
    result = Hash.new{ |k, v| k[v] = [] }

    self.comments.each do |comment|
      result[comment.parent_comment_id] << comment
    end

    result
  end
end

reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :is_author?, only: [:edit, :update, :destroy]
  before_action :require_logged_in

  # def new
  #   @post = Post.new
  #   @post.sub_id = sub_id
  # end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def update
    @post = Post.find_by(id: params[:id])

    if @post && @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = ["Invalid Post"]
      render :edit
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    @all_comments = @post.comments_by_parent_id
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    if @post && @post.destroy
      redirect_to subs_url(@post.sub_id)
    else
      flash[:errors] = ["You cannot destroy what is not there"]
      redirect_to post_url(@post)
    end
  end

  private

  def is_author?
    post = Post.find_by(id: params[:id])
    if post.author_id != current_user.id
      flash[:errors] = ["Not authorized to change post"]
      redirect_to post_url(post)
    end
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

reddit_clone/app/views/posts/_form.html.erb
<% method = post.persisted? ? "patch" : "post" %>
<% action = post.persisted? ? post_url(post) : posts_url %>
<% submit_text = post.persisted? ? "Update Post" : "Create New Post" %>

<form class="" action="<%= action %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="<%= method %>">

  <input type="hidden" name="post[sub_ids][]" value="">

  <% Sub.all.each do |subb| %>
    <label><%= subb.title %>
      <input
        type="checkbox"
        value="<%= subb.id %>"
        name="post[sub_ids][]"
        <%= "checked" if post.sub_ids.include?(subb.id) %>
      />
    </label>
  <% end %>



  <label for="">Title:
    <input type="text" name="post[title]" value="<%= post.title %>">
  </label>

  <label for="">Url:
    <input type="text" name="post[url]" value="<%= post.url %>">
  </label>

  <label for="">Content:
    <textarea name="post[content]" rows="8" cols="80"><%= post.content %></textarea>
  </label>

  <input type="submit" name="Submit Button" value="<%= submit_text %>">
</form>

reddit_clone/app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

reddit_clone/app/views/posts/new.html.erb
<%= render 'form', post: @post %>

reddit_clone/app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<h3><a href="<%= @post.url %>">URL</a></h3>
<p><%= @post.content %></p>

<%= link_to "Edit Post", edit_post_url(@post) %>
<br>
<%= link_to "Add Comment", new_post_comment_url(@post) %>

<h4>Comments:</h4>
<%# @post.comments.where(parent_comment_id: nil).each do |comment| %>
<% @all_comments[nil].each do |comment| %>
  <%# next if comment.parent_comment_id != nil %>
      <%#= link_to comment.content, comment_url(comment) %>

  <%= render 'comments/comment', parent_comment: comment, childhash: @all_comments %>
<% end %>