reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create, :show]

  root to: 'subs#index'
end

reddit_clone/app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :description, presence: true

  belongs_to :moderator, class_name: :User, foreign_key: :moderator_id, primary_key: :id

  has_many :post_subs, dependent: :destroy, inverse_of: :sub
  has_many :posts, through: :post_subs
end

reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :is_moderator?, only: [:edit, :update, :destroy]
  before_action :require_logged_in
  
  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find_by(id: params[:id])
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
  end

  def update
    @sub = Sub.find_by(id: params[:id])

    if @sub && @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = ["Invalid sub"]
      render :edit
    end
  end

  def destroy
    @sub = Sub.find_by(id: params[:id])
    if @sub
      @sub.destroy
      redirect_to subs_url
    else
      flash[:errors] = ["Cannot destroy what is not there.."]
      redirect_to subs_url
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def is_moderator?
    current_sub = Sub.find_by(id: params[:id])
    if current_sub.moderator_id != current_user.id
      flash[:errors] = ["Not authorized to change this sub"]
      redirect_to sub_url(current_sub)
    end
  end
end

reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

reddit_clone/app/views/subs/_form.html.erb
<% method = subb.persisted? ? "patch" : "post" %>
<% action = subb.persisted? ? sub_url(subb) : subs_url %>
<% submit_text = subb.persisted? ? "Update Sub" : "Create New Sub" %>

<form class="" action="<%= action %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="<%= method %>">

  <label for="">Title:
    <input type="text" name="sub[title]" value="<%= subb.title %>">
  </label>

  <label for="">Description:
    <input type="text" name="sub[description]" value="<%= subb.description %>">
  </label>

  <input type="submit" name="Submit Button" value="<%= submit_text %>">
</form>

reddit_clone/app/views/subs/edit.html.erb
<%= render 'form', subb: @sub %>

reddit_clone/app/views/subs/index.html.erb
<% @subs.try(:each) do |subb| %>
  <ul>
    <li>
      <%= link_to subb.title, sub_url(subb) %>
      <p>
        <%= subb.description %>
      </p>
    </li>
  </ul>
<% end %>

<%= link_to "Create Sub", new_sub_url %>

reddit_clone/app/views/subs/new.html.erb
<h1>Create Sub</h1>

<%= render 'form', subb: @sub %>

reddit_clone/app/views/subs/show.html.erb
<h2><%= @sub.title %></h2>

<h3>Description: </h3>
<p>
  <%= @sub.description %>
</p>

<h3>Posts: </h3>
<% @sub.posts.each do |post| %>
<ul>
  <li>
    <%= link_to post.title, post_url(post) %>
  </li>
</ul>
<% end %>

<h4>Create a Post:</h4>
<%= render 'posts/form', post: Post.new, sub_id: @sub.id %>

<%= link_to "Edit Sub", edit_sub_url(@sub) %>
<%= button_to "Delete Sub", sub_url(@sub), method: :delete %>