reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create, :show]

  root to: 'subs#index'
end

reddit_clone/app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :author, class_name: :User, foreign_key: :author_id, primary_key: :id
  belongs_to :post
  belongs_to :parent_comment,
    optional: true
  has_many :child_comments,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: :Comment
end

reddit_clone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @comment.post_id = params[:post_id]
    @comment.author_id = current_user.id
  end

  def create
    comment = Comment.new(comment_params)
    if comment.save
      redirect_to post_url(comment.post)
    else
      flash[:errors] = comment.errors.full_messages
      render :new
    end
  end

  def show
    # fail
    @comment = Comment.find_by(id: params[:id])
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :post_id, :author_id, :parent_comment_id)
  end
end

reddit_clone/app/helpers/comments_helper.rb
module CommentsHelper
  def display_comments(parent_comment)
    "<ul>".html_safe
    parent_comment.child_comments.each do |child|
      if child.child_comments.empty?

      end
    end
    "</ul>".html_safe
  end

  # <% @post.comments.each do |comment| %>
  #   <ul>
  #     <li>
  #       <% if comment.parent_comment_id.nil? %>
  #       <%= link_to comment.content, comment_url(comment) %>
  #
  #       <% end %>
  #     </li>
  #   </ul>
  # <% end %>
end

reddit_clone/app/views/comments/_comment.html.erb
<% children = childhash[parent_comment.id] %>
<ul>
  <li>(<%= children.length  %>)
  <%= link_to parent_comment.content, comment_url(parent_comment) %>
  </li>


  <% children.each do |child| %>
    <% if childhash[child.id].empty? %>
    <ul>
      <li>(<%= childhash[child.id].length  %>)
      <%= link_to child.content, comment_url(child) %></li>
    </ul>
    <% else %>
      <%= render 'comments/comment', parent_comment: child, childhash: childhash %>
    <% end %>
  <% end %>
</ul>

reddit_clone/app/views/comments/new.html.erb
<form class="" action="<%= comments_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="comment[author_id]" value="<%= @comment.author_id %>">
  <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>">
  <textarea name="comment[content]" rows="8" cols="80"></textarea>
  <input type="submit" name="submit" value="Add Comment">
</form>

reddit_clone/app/views/comments/show.html.erb
<header>
  Reply to Comment:
</header>

<form class="" action="<%= comments_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="comment[parent_comment_id]" value="<%= params[:id] %>">
  <input type="hidden" name="comment[post_id]" value="<%= @comment.post.id %>">
  <input type="hidden" name="comment[author_id]" value="<%= current_user.id %>">

  <textarea name="comment[content]" rows="8" cols="80"></textarea>

  <input type="submit" name="" value="Submit">
</form>

reddit_clone/app/views/comments/storage.html.erb
<ul>
  <li>(<%=parent_comment.child_comments.length  %>)
  <%= link_to parent_comment.content, comment_url(parent_comment) %>
  </li>


  <% parent_comment.child_comments.each do |child| %>
    <% if child.child_comments.empty? %>
    <ul>
      <li>(<%=child.child_comments.length  %>)
      <%= link_to child.content, comment_url(child) %></li>
    </ul>
    <% else %>
      <%= render 'comments/comment', parent_comment: child %>
    <% end %>
  <% end %>
</ul>

reddit_clone/app/views/comments/storage2.html.erb
<h2><%= @post.title %></h2>
<h3><a href="<%= @post.url %>">URL</a></h3>
<p><%= @post.content %></p>

<%= link_to "Edit Post", edit_post_url(@post) %>
<br>
<%= link_to "Add Comment", new_post_comment_url(@post) %>

<h4>Comments:</h4>
<% @post.comments.where(parent_comment_id: nil).each do |comment| %>


      <%#= link_to comment.content, comment_url(comment) %>

      <%= render 'comments/comment', parent_comment: comment %>


<% end %>